import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-gradient-to-br from-[#013735] to-black h-screen ${inter.className} overflow-hidden`}
      >
        <Header />
        <section className="flex">
          <Sidebar />
          <section className="flex flex-grow mt-20 h-screen">
            {children}
          </section>
        </section>
      </body>
    </html>
  );
}
