export const resolvers = {
  Query: {
    assignedTasks: () => {},
    attendedEvents: () => {},
    isAdmin: () => {},
    isactiveProject: () => {},
    currentUserTasks: () => {},
    openProjects: () => {},
    openTasks: () => {},
    eventAttendees: () => {},
    members: () => {},
  },
  Mutation: {
    createUser: () => {},
    createTask: () => {},
    createProject: () => {},
    createEvent: () => {},
    assignTask: () => {},
    attendEvent: () => {},
    updateTask: () => {},
    updateProjectLink: () => {},
    updateProjectDesctiprion: () => {},
    updateProjectStatus: () => {},
    updateUserRole: () => {},
    updateUserContactNo: () => {},
    removeProject: () => {},
    removeTask: () => {},
    removeEvent: () => {},
    removeAttendees: () => {},
  },
};
